spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_test
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /library


jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  duration:
    access-token: 300 # seconds
    refresh-token: 60 # seconds